name: AdminMode
description: $description
version: '${version}'

main: fr.ethilvan.adminMode.AdminModePlugin
api-version: '26.2'
load: POSTWORLD
softdepend: [ Multiverse-Inventories, LuckPerms ]

authors: [ Hironak ]
website: ethilvan.fr

commands:
  adminmode:
    aliases: [am]
    description: Enable/disable Admin Mode for the player executing this command
    usage: /<command>
permissions:
  adminmode.admin:
    default: op
  adminmode.use:
    default: op
  adminmode.savedefaultinventory:
    default: op
